In [86]:
import csv
import pandas as pd
import numpy as np
from pathlib import Path

In [87]:
filepath = '学生データベース.csv'
filepath_1 = '第１回_イントロダクション～人工知能と認知科学フィードバック.csv'
filepath_2 = '第2回_認知科学の考え方～情報処理の三水準.csv'
filepath_3 = '第３回_認知科学の方法.csv'
filepath_4 = '第４回_学術論文の構成 と 議論の進め方.csv'

In [89]:
df = pd.read_csv(filepath)
df = df.drop(['Unnamed: 0', 'Unnamed: 2'], axis=1, errors='ignore')
df_1 = pd.read_csv(filepath_1)
df_2 = pd.read_csv(filepath_2)
df_3 = pd.read_csv(filepath_3)
df_4 = pd.read_csv(filepath_4)

In [90]:
columns_name = ["第１回","第2回","第３回","第４回"]
df_list = [df_1,df_2,df_3,df_4]
for index, df_s in enumerate(df_list):
  for row_1 in df_s.itertuples():
    insert = True
    for row in df.itertuples():
      # print(getattr(row_1,"学生番号"),"------",getattr(row, "学籍番号"))
      # print(type(getattr(row_1,"学生番号")))
      # print(type(getattr(row, "学籍番号")))
      if not pd.isna(getattr(row_1,"学生番号")):
        if getattr(row_1,"学生番号") == str(getattr(row, "学籍番号")):
          print(getattr(row_1,"学生番号"),"------",getattr(row, "学籍番号"))
          df.at[row.Index,columns_name[index]] = 1
          insert = False
    if insert:
      print(getattr(row_1,"学生番号"))
      df = pd.concat([df, pd.DataFrame({'学籍番号':[getattr(row_1,"学生番号")],columns_name[index]:1})], ignore_index=True)

2410125 ------ 2410125
2310162
2410181
2410134
nan
2410220 ------ 2410220
2410072 ------ 2410072
2410221
2410115 ------ 2410115
2410081 ------ 2410081
s2310427
2410027 ------ 2410027
2410101 ------ 2410101
nan
2410098
2410168 ------ 2410168
2410068
nan
2410225 ------ 2410225
2410174
2310154
2410070
22B09
2410086 ------ 2410086
2410026
nan
2410147 ------ 2410147
2410053
2410093 ------ 2410093
2410143
2410147 ------ 2410147
2410101 ------ 2410101
2410057
2410026 ------ 2410026
2410222 ------ 2410222
2410220 ------ 2410220
s2310427 ------ s2310427
22B09 ------ 22B09
2410068 ------ 2410068
2410125 ------ 2410125
2410143 ------ 2410143
2410072 ------ 2410072
2410115 ------ 2410115
2410225 ------ 2410225
2410199 ------ 2410199
2410081 ------ 2410081
2410093 ------ 2410093
2410027 ------ 2410027
2450006
2410174 ------ 2410174
2410213
2410072 ------ 2410072
22B09 ------ 22B09
2410213 ------ 2410213
2410143 ------ 2410143
2410093 ------ 2410093
2410027 ------ 2410027
2410199 ------ 2410199
2410220 ------ 2410220
nan
2410125 ------ 2410125
s2310427 ------ s2310427
2410225 ------ 2410225
2410222 ------ 2410222
2410086 ------ 2410086
2410081 ------ 2410081
2410147 ------ 2410147
2410026 ------ 2410026
2410081 ------ 2410081
2410115 ------ 2410115
2410199 ------ 2410199
nan
s2310427 ------ s2310427
2410093 ------ 2410093
2410125 ------ 2410125
22B09 ------ 22B09
2410072 ------ 2410072
2410101 ------ 2410101
2410086 ------ 2410086
2410147 ------ 2410147
2410225 ------ 2410225
2410220 ------ 2410220

In [91]:
df

        学籍番号  0626グループワーク出席  0626出席  0630プレゼント  0701_出席  第１回  第2回  第３回  第４回
0    2110427            1.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
1    2130413            NaN     NaN        NaN      NaN  NaN  NaN  NaN  NaN
2    2310160            NaN     NaN        NaN      NaN  NaN  NaN  NaN  NaN
3    2310426            1.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
4    2310427            1.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
5    2410019            1.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
6    2410027            2.0     1.0        NaN      NaN  1.0  1.0  1.0  NaN
7    2410059            NaN     NaN        NaN      NaN  NaN  NaN  NaN  NaN
8    2410072            2.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
9    2410080            NaN     NaN        NaN      NaN  NaN  NaN  NaN  NaN
10   2410081            2.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
11   2410084            2.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
12   2410086            3.0     1.0        NaN      NaN  1.0  NaN  1.0  1.0
13   2410093            5.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
14   2410101            3.0     1.0        NaN      NaN  1.0  1.0  NaN  1.0
15   2410115            3.0     1.0        NaN      NaN  1.0  1.0  NaN  1.0
16   2410125            3.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
17   2410147            4.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
18   2410163            4.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
19   2410168            4.0     1.0        NaN      NaN  1.0  NaN  NaN  NaN
20   2410185            4.0     1.0        NaN      NaN  NaN  NaN  NaN  NaN
21   2410199            NaN     NaN        NaN      NaN  NaN  1.0  1.0  1.0
22   2410220            5.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
23   2410222            5.0     1.0        NaN      NaN  NaN  1.0  1.0  NaN
24   2410225            5.0     1.0        NaN      NaN  1.0  1.0  1.0  1.0
25   2310162            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
26   2410181            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
27   2410134            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
28       NaN            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
29   2410221            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
30  s2310427            NaN     NaN        NaN      NaN  1.0  1.0  1.0  1.0
31       NaN            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
32   2410098            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
33   2410068            NaN     NaN        NaN      NaN  1.0  1.0  NaN  NaN
34       NaN            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
35   2410174            NaN     NaN        NaN      NaN  1.0  1.0  NaN  NaN
36   2310154            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
37   2410070            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
38     22B09            NaN     NaN        NaN      NaN  1.0  1.0  1.0  1.0
39   2410026            NaN     NaN        NaN      NaN  1.0  1.0  1.0  NaN
40       NaN            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
41   2410053            NaN     NaN        NaN      NaN  1.0  NaN  NaN  NaN
42   2410143            NaN     NaN        NaN      NaN  1.0  1.0  1.0  NaN
43   2410057            NaN     NaN        NaN      NaN  NaN  1.0  NaN  NaN
44   2450006            NaN     NaN        NaN      NaN  NaN  1.0  NaN  NaN
45   2410213            NaN     NaN        NaN      NaN  NaN  1.0  1.0  NaN
46       NaN            NaN     NaN        NaN      NaN  NaN  NaN  1.0  NaN
47       NaN            NaN     NaN        NaN      NaN  NaN  NaN  NaN  1.0

In [92]:
df.to_csv('to_csv_out.csv')

In [ ]:
present_list = []
for row in df.itertuples():
  if not pd.isna(getattr(row, "第１回")):
    present_list.append(str(getattr(row, "学籍番号")))
present_list

In [94]:
len(present_list)

30

In [ ]:
import random
random.shuffle(present_list)

In [115]:
from pptx import Presentation
from pptx.util import Inches, Pt

prs = Presentation()

title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]

title.text = "認知科学概論 \n第６回 学術論文の要約報告会"
subtitle.text = "発表会"

slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(55)

for index,id in enumerate(present_list):
  
  title_slide_layout = prs.slide_layouts[0]
  slide = prs.slides.add_slide(title_slide_layout)
  title = slide.shapes.title
  subtitle = slide.placeholders[1]
  
  
  if index+1 != len(present_list):
    title.text = "発表者\n\n" + id + "     \n\n ( "+ str(index+1) + "/" + str(len(present_list)) +" )"
    subtitle.text = " \n \n \n次の発表者：" + present_list[index+1]
    slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(65)
  else:
    title.text = "発表者：" + id + "    \n ( "+ str(index+1) + "/" + str(len(present_list)) +" )"
    subtitle.text = " \n \n \n(最後の発表者)"
    slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(65)

title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]

slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(55)

title.text = "本日の発表は完了しました。"
subtitle.text = "ありがとうございます。!"



prs.save('test.pptx')